### ISSUE TITLE
megamenu level 2

### ISSUE THREAD

**Issue by andronic90** [ThemeFuse/Unyson-MegaMenu-Extension#1]
megamenu level 2 disapear description in backend , but in fronten appear. http://awesomescreenshot.com/0684b5k183 . 
When I put

**Comment by vbarbarosh** [comment]
Try to update MegaMenu to the latest version

**Comment by ghost** [comment]
@vbarbarosh [wrong latest version](http://static.md/fa0eaea22273fe92a9c3925e52f1c31f.png)

To publish a new release, you must [add it here](https://github.com/ThemeFuse/Unyson-Extensions-Approval) first. (You can set the release date today, if it's urgent)

**Comment by vbarbarosh** [comment]
https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/14
