### ISSUE TITLE
Modal change:values do not fire with custom icon

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson-MegaMenu-Extension#13]
I am trying to replace default icon option with my own and this filter works ok , 

```
function _thz_filter_menu_item_icon($icon) {

    $icon['type'] = 'thz-icon';
    $icon['label']  = __('Select icon', 'fw');
    //fw_print($icon);
    return $icon;
}


add_filter( 'fw:ext:megamenu:icon-option', '_thz_filter_menu_item_icon');
```

but the modal change is not registered

https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/blob/789389851602203a3bd27e027a2b80cc23cac584/static/js/admin.js#L101-L102

I have console log after  that line but not getting anything back if my option type is used. 

Here test it with icon-v2

```
function _thz_filter_menu_item_icon($icon) {

    $icon['type'] = 'icon-v2';
    $icon['label']  = __('Select icon', 'fw');
    //fw_print($icon);
    return $icon;
}


add_filter( 'fw:ext:megamenu:icon-option', '_thz_filter_menu_item_icon');
```

im basically trying to build that script that you have with default icon option type to work for my icon option also.

**Comment by ghost** [comment]
I refactored that js and now your link doesn't point to the right line

> https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/blob/master/static/js/admin.js#L102

Please give another link (better fixed to some commit, instead of master).

**Comment by danyj** [comment]
updated

**Comment by ghost** [comment]
1. Add your custom icon option type
   
   ``` php
   add_filter( 'fw:ext:megamenu:icon-option', '_filter_theme_fw_ext_megamenu_custom_icon');
   function _filter_theme_fw_ext_megamenu_custom_icon($icon) {
       $icon['type'] = 'icon-v2';
       $icon['label'] = __('Select icon', 'fw');
       return $icon;
   }
   ```
2. Use [this event](https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/blob/01b9fbf4c32ea93f1b1db2ebd1a3197b6d32508d/static/js/admin.js#L114) to convert your value format to simple `icon` option-type value
3. Use [this event](https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/blob/01b9fbf4c32ea93f1b1db2ebd1a3197b6d32508d/static/js/admin.js#L179) to convert simple `icon` option-type value format to your value
