### ISSUE TITLE
Item custom options must be enabled only for MegaMenu items

### ISSUE THREAD

**Issue by ghost** [ThemeFuse/Unyson-MegaMenu-Extension#14]
https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/259#issuecomment-245739519
- [x] Enable item options only for MegaMenu enabled items
- [x] Add the possibility to set different options for rows and columns

**Comment by ghost** [comment]
@danyj Item Options should be active only if "Use as Mega Menu" is checked?

**Comment by danyj** [comment]
@moldcraft , hm , I am not sure what you are making , so far I see is this 

mega row options , 
mega column options 
normal item options 

first 2 should be visible only if "Use as Mega Menu" is checked, 

last one has nothing to do with mega and should be available for other items if someone needs it ,

**Comment by ghost** [comment]
Done. Test please:
1. Download latest dev
2. Overwrite [these options](https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/tree/eb2d760afa11a2a52e0eb15d55490987416f9493/options) in theme
3. Get db value using [these functions](https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/blob/eb2d760afa11a2a52e0eb15d55490987416f9493/helpers.php#L153-L184) (the value structure is similar to [`multi-picker`](http://manual.unyson.io/en/latest/options/built-in-option-types.html#multi-picker-get-db-value) option-type)

**Comment by danyj** [comment]
@moldcraft ,  working on palette , will report back when done , day or 2 max.

**Comment by ghost** [comment]
I am not working on Unyson in weekend (only answer critical questions), so take your time.

**Comment by ghost** [comment]
Please let me know if you have tested it and it works fine, then I will create an [approval](https://github.com/ThemeFuse/Unyson-Extensions-Approval).

**Comment by danyj** [comment]
override works 
how do we change the settings popup size?

**Comment by danyj** [comment]
This works for me ,  dont know about others since now they dont have a hook for other items except megamenu and its items. But yes , works as intended. Just that popup size left to check .

**Comment by ghost** [comment]
> how do we change the settings popup size?

https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/commit/ad7c92f88614b0a6f4d698994ca610f85557b4d1

**Comment by danyj** [comment]
tested  works , all done

**Comment by ghost** [comment]
http://manual.unyson.io/en/latest/extension/megamenu/index.html#item-custom-options

**Comment by dinhtungdu** [comment]
For me, item options are not shown for normal item, only mega item. I think as we discussed, item option should be "mega-independent"?

**Comment by ghost** [comment]
@dinhtungdu Why do you need options for non megaMenu items?

**Comment by dinhtungdu** [comment]
@moldcraft For example with a social menu, I only want to show the icon, not the title. Or home route, many of my clients want to show only the home icon.

**Comment by dinhtungdu** [comment]
Another issue:

Notice: Object of class WP_Post could not be converted to int in /wp-content/plugins/unyson/framework/extensions/megamenu/helpers.php on line 183

**Comment by danyj** [comment]
> Another issue:

how to reproduce?

**Comment by dinhtungdu** [comment]
@danyj Sorry, double check and it's gone, calling wrong function (function used in previous commit).
@moldcraft How about the item option, do you tend to make it work with nonmega menu item?

**Comment by ghost** [comment]
@dinhtungdu [Done](https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/compare/7c5bd3c43d2f524c3194721424a31cb0d45d7359...281169555bd8d88d78025ba1b13bcc4bc83654a8) reDownload v1.1.0

**Comment by dinhtungdu** [comment]
All worked, done!

For row and column, should we make a view for them? Now I use custom Walker for megamenu customization.

**Comment by ghost** [comment]
At the moment I have other tasks to do, sorry. If you have a good idea how to implement views, please create a pull request.

**Comment by dinhtungdu** [comment]
Me too, submitting my theme, I will do it ASAP :)

**Comment by danyj** [comment]
@dinhtungdu  please watch for backwards compatibility, many devs are using it as it is now

**Comment by dinhtungdu** [comment]
@danyj ya, sure. But I think only solution right now is custom walker, so backwards compatibility won't be a big problem :)

**Comment by danyj** [comment]
@moldcraft  

> Get db value using these functions (the value structure is similar to multi-picker option-type)

how do we do this within megamenu static.php 
https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/blob/master/static.php

 , wee need a loop but I dont know what available atts if any we have there .

**Comment by danyj** [comment]
@moldcraft  I am missing something here ,  


```
if (!is_admin()) {
	
	
	$locations 	= get_nav_menu_locations();
	$menu 		= wp_get_nav_menu_object( $locations[ 'mainmenu' ] );
	$menuitems 	= wp_get_nav_menu_items( $menu->term_id );

	
	
	foreach ($menuitems as $menuitem){
		
		$id = $menuitem->ID;
		$mega_bs = fw_ext_mega_menu_get_db_item_option($id,'mega_bs');
		fw_print($mega_bs);
	}
	
}
```


menu item ID's are there , option name is mega_bs ,  the function requires , 

item ( ID )  and option name , I am not getting anything out

**Comment by danyj** [comment]
got it , 

	$locations 	= get_nav_menu_locations();
	$menu 		= wp_get_nav_menu_object( $locations[ 'mainmenu' ] );
	$menuitems 	= wp_get_nav_menu_items( $menu->term_id );

	
	
	foreach ($menuitems as $menuitem){
		
		$id = $menuitem->ID;
		$item_type = fw_ext_mega_menu_get_db_item_option($id,'type');
		
		if($item_type == 'row'){
			
			$mega_bs = fw_ext_mega_menu_get_db_item_option($id,'row/mega_bs');
			
			fw_print($mega_bs);
		
		}
	}
