### ISSUE TITLE
How to add more attributes to <li> tag.

### ISSUE THREAD

**Issue by themesmeta** [ThemeFuse/Unyson-MegaMenu-Extension#15]
Hi,
I'm trying to add more attributes to `<li>` tag here 
https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/blob/master/includes/class-fw-ext-mega-menu-walker.php#L52
What is the best way to do this ?
Any help would be appreciated. Thanks.

**Comment by dinhtungdu** [comment]
Right now the only way I know is [custom walker](http://manual.unyson.io/en/latest/extension/megamenu/index.html#overwrite-the-walker).
