### ISSUE TITLE
Replace Icon option in mega menu by icon-v2

### ISSUE THREAD

**Issue by dinhtungdu** [ThemeFuse/Unyson-MegaMenu-Extension#16]
As title say, please consider updating this, it's full of pain when searching for right icon in v1.

**Comment by ghost** [comment]
It's not possible because [`icon-v2`](https://github.com/ThemeFuse/Unyson/blob/a0fc5ffdadc711d9d2f487dd65b6d74cf5b31524/framework/includes/option-types/icon-v2/class-fw-option-type-icon-v2.php#L176-L188) and [`icon`](https://github.com/ThemeFuse/Unyson/blob/a0fc5ffdadc711d9d2f487dd65b6d74cf5b31524/framework/includes/option-types/icon/class-fw-option-type-icon.php#L127) db values structure are different.

**Comment by dinhtungdu** [comment]
Thinking about backward compat, may be replacing isn't so smart. An idea I have now is a filter to switch to v2, or a filter to hide icon then developers can add icon-v2 in item-option.

**Comment by ghost** [comment]
If you have a good idea, please pull request.

**Comment by dinhtungdu** [comment]
What about a filter to hide the icon option, then developers can add their own icon in item-option?

**Comment by ghost** [comment]
Seems to be fine.

**Comment by dinhtungdu** [comment]
I think only hide is a safer. My solution is only hide this by add a filter in bellow and change a bit in `admin.js` to show setting button when icon is hidden. What do you think? I can make a pull now. 

```
    public function _admin_filter_manage_nav_menus_columns($columns)
    {
        $columns['icon'] = __('Icon', 'fw');

        return $columns;
    }
```

**Comment by andreiglingeanu** [comment]
`icon-v2`'s value is always an `array`, for the first version we've got only a string: `fa fa-heart`.

I see no problem detecting a string in DB and try to convert it to new syntax - as long as developers are okay with having to pipe values of `v1` through a custom function.

<hr>

I may be able to come up later with a detailed approach on how to migrate away from v1 in a painless way but that's totally not what I'm currently focused.

The `icon-v2` goal was not be a drop-in replacement of the first version. Everyone's gonna gradually transition to it.

<hr>

@dinhtungdu Please make this option hiding an opt-in feature (hide it behind a filter or config option and enable it in your theme), not a default one.

<hr>

One more idea is to make icon picker version configurable and keep V1 as a default. The guys who didn't yet released their theme will have an easy time making the switch.

**Comment by dinhtungdu** [comment]
There is an other problem related to the icon option. the Setting button is append to icon. When the user hides Icon in Screen option, the setting button won't show up. I think we should keep this independence to icon option.

Like this (http://prntscr.com/cyd12j)

**Comment by ghost** [comment]
https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/blob/v1.1.1/class-fw-extension-megamenu.php#L82

It will work when this will be fixed https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/issues/13
