### ISSUE TITLE
Delegate render to views in frontend walker instead of walker overwrite in theme

### ISSUE THREAD

**Issue by dmbostan** [ThemeFuse/Unyson-MegaMenu-Extension#18]
Hi everyone!

Is there a way to change the HTML output for secondary level items? Like adding values of options?

**Comment by dinhtungdu** [comment]
For now, AFAIK, you have to use a custom Walker to do it. Currently, only view for item link is available.

**Comment by dmbostan** [comment]
Thank you, @moldcraft !
