### ISSUE TITLE
Issue with menu icons

### ISSUE THREAD

**Issue by thanhluu** [ThemeFuse/Unyson-MegaMenu-Extension#3]
I meet problem with using icon on menu. Classes of icon `fa fa-...` are directly inserted into <a> tag. Although, it will cause error when I want style font of that menu item. So, can you provide a solution to insert icon into <i> tab with markup as below:
`<a href="..."><i class="fa fa-..."></i> Menu label</a>`

Regards,
Thanh Luu

**Comment by ghost** [comment]
You can overwrite [this view](https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/blob/master/views/item-link.php) in your theme by creating

```
{theme}/framework-customizations/extensions/megamenu/views/item-link.php
```

with the following contents:

``` php
<?php if (!defined('FW')) die('Forbidden');

/**
 * @var WP_Post $item
 * @var string $title
 * @var array $attributes
 * @var object $args
 * @var int $depth
 */

{
    $icon_html = '';

    if (
        fw()->extensions->get('megamenu')->show_icon()
        &&
        ($icon = fw_ext_mega_menu_get_meta($item, 'icon'))
    ) {
        $icon_html = '<i class="'. $icon .'"></i> ';
    }
}

// Make a menu WordPress way
echo $args->before;
echo fw_html_tag('a', $attributes, $args->link_before . $icon_html . $title . $args->link_after);
echo $args->after;
```

**Comment by moldcraft** [comment]
I can't change that view, because some themes may be using that default view and changing it will broke their styles.

**Comment by ghost** [comment]
I can't change that view, because some themes may be using that default view and changing it will broke their styles.

For example our scratch theme with default view looks like [this](http://static.md/069244a5de6cf2c1079d9f05e1089edc.png) but with the above fix it looks like [this](http://static.md/2e286583bb8fcbdd7db4ff472f4f38de.png).

**Comment by thanhluu** [comment]
That's exactly what I was looking for. Thank you!
