### ISSUE TITLE
Plugin Compatibility: Nav Menu Roles

### ISSUE THREAD

**Issue by 2Fwebd** [ThemeFuse/Unyson-MegaMenu-Extension#5]
Hi, 

There is a compatibility issue with Nav Menu Roles and the Mega menu extension, it's a really active plugin with more than 50 000 + active installs. So that'll be nice to have it compatible with this wonderful extension ;) 

It has been reported by one of our customer and he found a fix : 

![4221272614](https://cloud.githubusercontent.com/assets/5446124/10124444/7ba1d606-6555-11e5-8d95-aeb0b018c2fa.png)

(in the admin-walker file)

See : https://wordpress.org/plugins/nav-menu-roles/faq/

Let me know if you need more details. 

Best regards,

2F

**Comment by linjo** [comment]
Can I fix this issue in the theme folder? I cant redeclare the FW_Ext_Mega_Menu_Admin_Walker  class in theme right? I hope I should add this fix in the megamenu in plugins folder?

Please correct me if I am wrong.
Thanks

**Comment by ghost** [comment]
@linjo You can't wait 3 days? https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/223

**Comment by linjo** [comment]
Its for my client , little urgent

On 31 May 2016 at 17:37, moldcraft notifications@github.com wrote:

> @linjo https://github.com/linjo You can't wait 3 days?
> ThemeFuse/Unyson-Extensions-Approval#223
> https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/223
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/issues/5#issuecomment-222669327,
> or mute the thread
> https://github.com/notifications/unsubscribe/ALGnCcVKgV_Iu6UwUhiTaajCc-h5UG3Bks5qHCR4gaJpZM4GEi1f
> .

## 

Linjo Joson

**Comment by ghost** [comment]
Try in theme

``` php
add_filter('wp_edit_nav_menu_walker', '_filter_theme_fw_ext_megamenu_custom_walker', 12);
function _filter_theme_fw_ext_megamenu_custom_walker($class_name) {
    return 'FW_Theme_Ext_Mega_Menu_Admin_Walker';
}
```

``` php
class FW_Theme_Ext_Mega_Menu_Admin_Walker extends FW_Ext_Mega_Menu_Admin_Walker {
    // overwrite https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/blob/v1.0.11/includes/class-fw-ext-mega-menu-admin-walker.php
}
```

**Comment by linjo** [comment]
That fixed it.  Thanks guys!

On 31 May 2016 at 18:00, moldcraft notifications@github.com wrote:

> Try in theme
> 
> add_filter('wp_edit_nav_menu_walker', '_filter_theme_fw_ext_megamenu_custom_walker', 12);function _filter_theme_fw_ext_megamenu_custom_walker($class_name) {    return 'FW_Theme_Ext_Mega_Menu_Admin_Walker';}
> 
> class FW_Theme_Ext_Mega_Menu_Admin_Walker extends FW_Ext_Mega_Menu_Admin_Walker {    // overwrite https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/blob/v1.0.11/includes/class-fw-ext-mega-menu-admin-walker.php}
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/issues/5#issuecomment-222674099,
> or mute the thread
> https://github.com/notifications/unsubscribe/ALGnCW1nCx79JL6QLwE4qnSv02z0VjyNks5qHCnigaJpZM4GEi1f
> .

## 

Linjo Joson
