### ISSUE TITLE
Screen options toggle nav menu on WP 4.4

### ISSUE THREAD

**Issue by fauzie** [ThemeFuse/Unyson-MegaMenu-Extension#6]
WP 4.4 seems dosn't have id attribute for checkbox at screen options "Show advanced menu properties". Change checkbox selector for icon.

File "static/js/admin.js" Line 7

``` javascript
var selector = '.hide-column-tog[name="icon-hide"]';
```

Issue also found on Title Attribute checkbox, but i don't know how to fix it.

**Comment by ghost** [comment]
Thank you

**Comment by 2Fwebd** [comment]
Hi there, 

Is the update already available ? We have a lot requests about that issue. We fix it for now with some CSS patch. But I still have some issue with it and WP 4.4. 

Let me know if you need more details.

**Comment by ghost** [comment]
Sorry, forgot to press Publish Release https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/166

**Comment by 2Fwebd** [comment]
Thank you @moldcraft ! :)
