### ISSUE TITLE
Getting undefined index icon when adding new menu item,

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson-MegaMenu-Extension#7]
```
Notice: Undefined index: icon in ...\unyson\framework\extensions\megamenu\class-fw-extension-megamenu.php on line 119
```

``` php
fw_ext_mega_menu_update_meta($menu_item_db_id, array(
    'enabled' => isset($meta['enabled']),
    'title-off' => isset($meta['title-off']),
    'new-row' => isset($meta['new-row']),
    'icon' => $meta['icon'],  //---- this one here
));
```

but looking  now at git mega menu class and my local they are not same . So seems like the update was not ok  and I have no notices to update the extesion, 

I have 161 lines where the git version has 127

**Comment by ghost** [comment]
1. How to test this (the exact steps) ?
2. It works with the latest git version?

**Comment by danyj** [comment]
I am sure it does work with latest , why I posted this is because I did not and do not have notification to update the mega menu and by the looks of it seems like I have an old version.

**Comment by ghost** [comment]
The update parameter [is there](https://github.com/ThemeFuse/Unyson-MegaMenu-Extension/blob/v1.0.0/manifest.php#L13) from v1.0.0. I lowered that version manually and the update appeared

![](http://static.md/ba375514f1e9db6feeaaecf0eb728ac6.png)

**Comment by danyj** [comment]
this is why 
http://prntscr.com/ai2pmm

mines says 1.1.0, have no idea how.

lowered and updated.

**Comment by ghost** [comment]
Please do not delete that extension! I think your PC traveled in future and updated the extension. It will be useful in fixing future bugs, maybe in it they are all fixed.
