### ISSUE TITLE
Mega Menu column meta options are not working

### ISSUE THREAD

**Issue by Nikschavan** [ThemeFuse/Unyson-MegaMenu-Extension#9]
The mega menu column checkboxes for _Mega Menu Column Title _ and _This column should start a new row_ are not being saved.

The value is not retained after the menu is saved. [screenshot](http://goo.gl/zxBwU0)

Using - 
latest Unyson Framework v 2.5.3 
latest mega menu extension - v1.0.9
Latest WordPress 4.5

**Comment by Nikschavan** [comment]
Just confirmed, This works perfectly with WordPress 4.4.2, latest Unyson Framework v 2.5.3 
latest mega menu extension - v1.0.9.

The problem seems after WordPress 4.5

**Comment by ghost** [comment]
https://core.trac.wordpress.org/ticket/36590#ticket
